#!/bin/bash

USERID=(id -u)
DATE=$(date +%F)
LOG="jenkins-install-${DATE}.log"
R="\e[31m"
G="\e[32m"
N="\e[0m"

VALIDATE(){

if [ $1 -ne 0 ]; then
    echo -e "$2 is  ${R} failure ${N}" 2>$1 | tee -a $LOG
    exit 1
else
    echo -e "$2 is ${G} success ${N}" 2>$1  | tee -a $LOG
fi
}

#check the user is root or not

if [ $USERID -ne 0 ]; then
   echo "You need to root user then execute script"
   exit 1
fi

yum update -y  &>>$LOG

VALIDATE $? "updating yum"

sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo  &>>$LOG
	
VALIDATE $? " Addingjenkins repo"

sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key  &>>$LOG

VALIDATE $? "Import jenkins key"

sudo yum upgrade  &>>$LOG

VALIDATE $? "yum upgrade"

sudo dnf install java-17-amazon-corretto -y  &>>$LOG

VALIDATE $? "install java"

sudo yum install jenkins -y  &>>$LOG

VALIDATE $? "install jenkins"

sudo systemctl start jenkins  &>>$LOG

VALIDATE $? "start jenkins"

sudo systemctl status jenkins  &>>$LOG

VALIDATE $? "status jenkins"

