#!/bin/bash

USERID=(id -u)

VALIDATE(){

if [ $1 -ne 0 ]; then
  echo" $2 is failure"
  exit 1
else
  echo" $2 is success"
fi
}

#check the user is root or not

if [ $USERID -ne 0 ]; then
  echo"if the user is root then execute script"
  exit 1
fi

yum update -y
VALIDATE $? "updating yum"

sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
VALIDATE $? "jenkins repo"

sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
VALIDATE $? "jenkins key"

sudo yum upgrade
VALIDATE $? "yum upgrade"

sudo dnf install java-17-amazon-corretto -y
VALIDATE $? "install java"

sudo yum install jenkins -y
VALIDATE $? "install jenkins"

sudo systemctl start jenkins
VALIDATE $? "start jenkins"

sudo systemctl status jenkins
VALIDATE $? "status jenkins"
